/**
 * Website continued development prompt generation utility
 *
 * Provides functionality to generate prompts for continued development
 * in Agent Chat based on generated website code.
 */

import { SandpackBundlerFiles } from '@codesandbox/sandpack-client'
import { extractWebsiteCode, getMainFilePaths } from './websiteCodeExtractor'
import { Style, SupportedTemplate } from '../templates'

/**
 * Generate prompt for website continued development
 *
 * @param files Sandbox file structure
 * @param template Currently used template
 * @param styleType Currently used style type
 * @param userDescription User-entered description (optional)
 * @returns Prompt string for continued development
 */
export const generateContinueDevelopmentPrompt = (
  files: SandpackBundlerFiles,
  template: SupportedTemplate['id'],
  styleType: Style,
  userDescription?: string
): string => {
  // Extract website code
  const codeContent = extractWebsiteCode(files)
  const mainFilePaths = getMainFilePaths(files)

  // Format template information
  const templateInfo = `Template: ${template}, Style: ${styleType.label}`

  // Main files information
  const mainFilesInfo = mainFilePaths.length > 0 ? `Main files: ${mainFilePaths.join(', ')}` : ''

  // User description section
  const descriptionSection = userDescription ? `\n\n## Website Overview\n${userDescription}` : ''

  // Build complete prompt
  return `# Website Continued Development

The following code is an initial website generated by WebsiteGenerator.
Please help improve and extend this website with additional features.

${templateInfo}
${mainFilesInfo}
${descriptionSection}

## Current Website Code

${codeContent}

## Request

I would like to implement the following improvements and feature additions for this website:
1. UI/UX improvements
2. Responsive design optimization
3. Feature additions and extensions

Please suggest what improvements are possible. If specific features or design changes are requested, please provide corresponding code implementations.`
}
